In [32]:
import numpy as np
A = np.random.randint(1, 5, size=(3,4))
print(A)

[[4 3 2 2]
 [2 2 4 1]
 [4 4 4 3]]


In [33]:
U,D,V = np.linalg.svd(A)
#Matriz D de diagonales se debe de completar con 0 para que se pueda multiplicar con V, de acuerdo a la forma de este
D = np.concatenate((np.diag(D),np.zeros(shape=(3,1))),axis=1)
print(U.shape,D.shape,V.shape)
A_calc = U.dot(D).dot(V)
print('Matriz original\n',A,'\nMatriz calculada\n',A_calc)

(3, 3) (3, 4) (4, 4)
Matriz original
 [[4 3 2 2]
 [2 2 4 1]
 [4 4 4 3]] 
Matriz calculada
 [[4. 3. 2. 2.]
 [2. 2. 4. 1.]
 [4. 4. 4. 3.]]
