### Descomposici****ó****n 1

Pero en estos casos en función de la matriz de autovectores y autovalores.

In [3]:
import numpy as np

A = np.array([[3,2],[4,1]])
autovalores,autovectores = np.linalg.eig(A)
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
print('Matriz A:\n',A,'\nMatriz A calculada\n',A_calc)

Matriz A:
 [[3 2]
 [4 1]] 
Matriz A calculada
 [[3. 2.]
 [4. 1.]]


### Descomposici****ó****n 2

Que tengamos una matriz simétrica (A=A.T) y con números reales. Decimos que A = la matriz de autovectores producto punto la matriz diagonal con los autovalores, producto punto la transpuesta de la matriz de autovectores.

In [5]:
import numpy as np

A = np.array([[3,2],[2,3]])
#Cumpliendo restriccion
print(A == A.T)
autovalores,autovectores = np.linalg.eig(A)
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print('Matriz A:\n',A,'\nMatriz A calculada\n',A_calc)

[[ True  True]
 [ True  True]]
Matriz A:
 [[3 2]
 [2 3]] 
Matriz A calculada
 [[3. 2.]
 [2. 3.]]
